//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Bills = new HashSet<Bill>();
            this.BranchImports = new HashSet<BranchImport>();
            this.HeadImports = new HashSet<HeadImport>();
            this.RequestImports = new HashSet<RequestImport>();
        }
    
        public string IDAcc { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string idCard { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Auth { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<BranchImport> BranchImports { get; set; }
        public virtual ICollection<HeadImport> HeadImports { get; set; }
        public virtual ICollection<RequestImport> RequestImports { get; set; }
    }
}
