//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_List
    {
        public string IDBill { get; set; }
        public string IDProduct { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
