//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Bill_List = new HashSet<Bill_List>();
        }
    
        public string IDBill { get; set; }
        public string IDAcc { get; set; }
        public System.DateTime Date { get; set; }
        public string POS { get; set; }
        public double TotalAmount { get; set; }
        public int TotalQuantity { get; set; }
        public double Receive { get; set; }
        public double Change { get; set; }
        public string IDProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Bill_List> Bill_List { get; set; }
        public virtual Product Product { get; set; }
    }
}
