//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadImport
    {
        public HeadImport()
        {
            this.BranchImports = new HashSet<BranchImport>();
            this.HeadImport_List = new HashSet<HeadImport_List>();
        }
    
        public string IDHead { get; set; }
        public string IDRequest { get; set; }
        public string IDAcc { get; set; }
        public System.DateTime Date { get; set; }
        public double TotalAmount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BranchImport> BranchImports { get; set; }
        public virtual ICollection<HeadImport_List> HeadImport_List { get; set; }
        public virtual RequestImport RequestImport { get; set; }
    }
}
