//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestImport
    {
        public RequestImport()
        {
            this.HeadImports = new HashSet<HeadImport>();
            this.RequestImport_List = new HashSet<RequestImport_List>();
        }
    
        public string IDRequest { get; set; }
        public System.DateTime Date { get; set; }
        public string IDSupplier { get; set; }
        public string IDAcc { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<HeadImport> HeadImports { get; set; }
        public virtual ICollection<RequestImport_List> RequestImport_List { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
